export const memberFieldMap: {[key: string]: string} = {
    'FIRST NAME': 'first_name',
    'LAST NAME': 'last_name',
    'SSN': 'ssn',
    'UNIQUE MEMBER ID': 'member_id',
    'SEQUENCE NUMBER': 'sequence_num',
    'DEPENDENT TYPE': 'dependent_type',
    'DATE OF HIRE': 'date_of_hire',
    'BILLING FREQUENCY': 'billing_freq',
    'DEDUCTION': 'deduction_freq',
    'DATE OF BIRTH': 'date_of_birth',
    'GENDER': 'gender',
    'CELL PHONE': 'phone_num',
    'OTHER PHONE': 'other_phone',
    'EMAIL': 'email',
    'ADDRESS LINE 1': 'address_line1',
    'ADDRESS LINE 2': 'address_line2',
    'CITY': 'city',
    'STATE': 'state',
    'ZIP CODE': 'zip_code',
    'HSA': 'hsa',
    'EFFECTIVE DATE': 'effective_date',
    'TERMINATION DATE': 'termination_date',
    'EARLY ACCESS DATE': 'early_access_date',
    'NOTES': 'notes',
}
