export enum MembersRolePermissionsDefault {
    CREATE_CLIENT = 'create:client',
    READ_CLIENT = 'read:client',
    UPDATE_CLIENT = 'update:client',
    DELETE_CLIENT = 'delete:client',
    CREATE_MEMBER = 'create:member',
    READ_MEMBER = 'read:member',
    UPDATE_MEMBER = 'update:member',
    DELETE_MEMBER = 'delete:member',
    CREATE_INVOICE = 'create:invoice',
    READ_INVOICE = 'read:invoice',
    UPDATE_INVOICE = 'update:invoice',
    DELETE_INVOICE = 'delete:invoice',
    CREATE_BROKER = 'create:broker',
    UPDATE_BROKER = 'update:broker',
    READ_BROKER = 'read:broker',
    DELETE_BROKER = 'delete:broker',
}
